#!/usr/bin/env ruby

require "substrate_client"
require "json"

# metadata url block_hash
url = ARGV[0] || "wss://cc3-5.kusama.network/"
block_hash = ARGV[1]

client = SubstrateClient.new(url)
client.init(block_hash)
metadata = client.get_metadata(block_hash)
puts JSON.pretty_generate(metadata.value)
