#!/usr/bin/env ruby

require "substrate_client"
require "json"

url = ARGV[0] || "wss://kusama-rpc.polkadot.io/"
client = SubstrateClientSync.new(url)

block_hash = ARGV[1] || client.chain_get_finalised_head

metadata = client.get_metadata(block_hash)
puts JSON.pretty_generate(metadata.value.to_human)
